### ISSUE TITLE
how to make ApiResponse  as Error?

### ISSUE THREAD

**Issue by Windforce17** [poem-web/poem#162]
In some case,I need to return some useful message like this:
```json
{
"error_hint":"xxx length too long"
}
```
I also want use Resut as function returrn type in order to use `?` operator,but how to generate `poem::error::Error` type from Json?

**Comment by sunli829** [comment]
Maybe this example can help you.

https://github.com/poem-web/poem/tree/master/examples/openapi/uniform-response

**Comment by Christoph-AK** [comment]
Looking at your generic solution it is a bit shorter then my macro one, but my solution has two advantages: I can use `?` in my code to convert errors implicitly, and my ResponseTypes get named explicitly so that swagger shows them as e.g. `GetRecipeType` instead of I assume `MyResponse<Vec<Recipe>>` or the like. 

I ran into some compiler limitations regarding having too many macros in the same `Use`-line which I needed to split, but other than that it seems to run fine now its implemented.
