### ISSUE TITLE
Breaking change in ParseFromJSON and ToJSON

### ISSUE THREAD

**Issue by glebpom** [poem-web/poem#200]
## Expected Behavior
No breaking changes of public interface in minor version upgrade

## Actual Behavior
Breaking change led to changes in the public interface in openapi types [here](https://github.com/poem-web/poem/commit/85f3496027ddc3a7a9e066d552fdc52dc7ce4bb1#diff-b721625036dde3b5978fa7c2b6b87a7b356af960674fda8d553b010a97a29b1d)

**Comment by Christoph-AK** [comment]
+1 this. 

As in https://github.com/poem-web/poem/blob/c49d813f884934b350826a922d720ab314c4723f/poem-openapi/CHANGELOG.md?plain=1#L5 poem should keep more in line with semver. 

I understand that it's really annoying to keep track of while developing, but for consumers of the lib this would help big time, especially with having poem deployed in production.

Maybe a simpler SemVer-interpretation could be enough here:

- Break an API? Increase first (major) number.
- Add anything without breaking existing API? Increase second (minor) number.
- Fix a bug without adding functionality and breaking existing api? Increase third (patch) number.

Most changes to poem would be major or minor version updgrades then, but that is totally okey and desired. 

As someone else put it in another issue: "It is fine to install poem v140.35.3, but it is not desirable to do a patch upgrade and have the API change."

It is okey to do mistakes in the process and have a few versions here and there that do not follow SemVer and break something, but it would be an awesome start to have those be the exception instead of having russian roulette with every release.

**Comment by glebpom** [comment]
That was easy - my code stopped compiling 😄 Poem is a neat project, and is used in real production. I'd prefer a rapid major version bump, rather than breaking changes after a simple `cargo update`.

**Comment by Christoph-AK** [comment]
@glebpom I made it a habit to specify exact version number in consuming programs. That way I at least need to manually research and specify the changing version (VSCode 'crates' extension helps with this) and can draw a link between what dependency I updates and what part of the code broke, and probably have a safer deployment because there won't be any surprises.
