### ISSUE TITLE
Integrations tests

### ISSUE THREAD

**Issue by jonathanblade** [poem-web/poem#274]
I wrote some integration tests for my app like this:

```rust
// tests/user_tests.rs

#[tokio::test]
#[serial_test::serial]
async fn get_all_users() {
// some code
}

#[tokio::test]
#[serial_test::serial]
async fn get_user() {
// some code
}
```

At the beginning of each test, I create `TestClient` and reset with SQLx (drop and create) the database. The problem is that between tests `get_all_users` and `get_user` from the same file, the database doesn't reset. If each test put in a separate file, then all will be ok. There was no such problem with [Rocket.rs](https://rocket.rs). Could this be a bug or is it my fault?

**Comment by sunli829** [comment]
I don't think this is caused by Poem. 🙂

**Comment by ChillFish8** [comment]
I think you may just been running into the fact that the tests are run in parallel, not caused by poem, but just by the nature of the unit tests. You probably want to set the test concurrency there to be `1` rather than `n` threads. 

The reason why this works with separate files is that they'll then be run sequentially (although not guaranteed IIRC)


https://doc.rust-lang.org/cargo/commands/cargo-test.html
```shell
cargo test foo -- --test-threads 1
```
